### ISSUE TITLE
Mozilla claims extension won't work on Firefox versions 43 and above

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/CarbonFootprint#120]
<img width="659" alt="screen shot 2016-10-13 at 09 33 06" src="https://cloud.githubusercontent.com/assets/1809436/19330467/4a326ed0-912a-11e6-9128-52b63dbd38f9.png">

**Comment by Kolpa** [comment]
Doesn't that just mean it won't work while it is not reviewed though? I'd like to see if it still says that when the Review is done.

**Comment by Ceilican** [comment]
Ah, yes. You are right. I have just found this text, which explains it better:

![screen shot 2016-10-13 at 09 57 56](https://cloud.githubusercontent.com/assets/1809436/19330705/b5bb952c-912b-11e6-9556-19bdcc5a5a81.png)

It is annoying when people write just "and" when they actually mean "and therefore"...
