### ISSUE TITLE
Installing CarbonFootprint  error     -bash: gulp: command not found on Mac Os

### ISSUE THREAD

**Issue by boro741** [OiWorld/CarbonFootprint#121]
I've run the commands as instructed in the README file.

But when I run gulp groupChrome it says gulp command not found.

Also, I tried to install gulp using npm install -g gulp
command.
So even after installing gulp it gives me the same error.

![screen shot 2016-10-20 at 7 10 06 am](https://cloud.githubusercontent.com/assets/16509376/19543659/c3d7c57a-9696-11e6-8944-40abdd1e4f1a.png)

**Comment by Kolpa** [comment]
This should not happen when gulp is properly installed, are you sure gulp is working outside of the project/can you rerun npm install -g gulp.

**Comment by boro741** [comment]
I've run successfully gulp groupChrome.
But now how can I use it ?
On the instructions given in README, it says "for chrome, load the unpacked extension from the Build/Chrome folder"
So I've found the Build folder-->Chrome.

So what should I suppose to do to run?

**Comment by Kolpa** [comment]
If you just want to run the plugin you can install it from the chrome webstore at https://chrome.google.com/webstore/detail/carbon-footprint/ednfpjleaanokkjcgljbmamhlbkddcgh

If you want to do development i suggest reading up on how to use plugins in development mode in chrome especially this part which tells you exactly how to load a unpacked extension. https://developer.chrome.com/extensions/getstarted#unpacked

**Comment by boro741** [comment]
Thank you.

**Comment by Kolpa** [comment]
No Problem :)
