### ISSUE TITLE
Migrating Safari port to a Safari App Extension

### ISSUE THREAD

**Issue by heychirag** [OiWorld/CarbonFootprint#137]
Apple has come up with new platform called Safari App Extension. It's a native macOS app that can work as an extension to Safari and could also interact with the macOS itself. The benefit of this would be that we could list our app directly on the macOS app store instead of the Safari Extension Gallery. This could help in reaching out to more users. Also, some extra features (such as a menu bar preference pane) can be added since it would a native macOS app.

The official guide to build a Safari App Extension can be found [here](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/SafariAppExtension_PG/)

**Comment by ceilican** [comment]
This idea seems interesting.

**Comment by ceilican** [comment]
Apple is still reviewing our extension, by the way... That's why it hasn't appeared in the extension gallery yet.

**Comment by ceilican** [comment]
This issue has been migrated to our new issue tracker in GitLab. Please continue discussions [here](https://www.gitlab.com/aossie/CarbonFootprint/issues/136).
